Implement xmallocs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-PARAMS="-std=c99"
+PARAMS="-std=c99 -save-temps"
 DEBUG=true
-OPTIMIZATION="-O"
+OPTIMIZATION="-O0"
 WARNINGS=""
 ERRS="-pedantic-errors"
 DEFS=""
@@ -24,7 +24,7 @@ CPARAMS="$PARAMS $WARNINGS $ERRS"
 
 if $DEBUG
 then
-    CPARAMS="$CPARAMS -g -Og -DDEBUG"
+    CPARAMS="$CPARAMS -g -O0 -DDEBUG"
 else
     CPARAMS="$CPARAMS $OPTIMIZATION -DNDEBUG"
 fi
@@ -77,7 +77,8 @@ do
     # the rm check \$@ could use -f, but it shouldn't be necessary
     printf "$TESTDIR/%s\n\t$CC -c -o \$@ \$(CPARAMS) \$< \
         \n\t$CC -o check \$(LPARAMS) \$@ %s \$(LINKS) \
-        \n\ttput setaf 2; if ! ./check; then tput setaf 1; echo 'Check failed!'; tput sgr 0; rm check; exit 1; else tput sgr 0; fi \
+        \n\ttput setaf 1; if ! ./check; then echo 'Check failed!'; tput sgr 0; rm check; exit 1; else tput sgr 0; fi \
+        \n\ttput setaf 2; echo 'Check succeeded!'; tput sgr 0 \
         \n\trm check \$@" \
         "$($CC -MM $TEST)" \
         "$(printf "%s" "$TEST" | sed -e "s/$TESTDIR/$SRCDIR/" | \
